name: build protobuf
on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev libprotoc-dev protobuf-compiler
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install npm deps
        run: |
          make npm/deps
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          echo "checkout master"
          git checkout master
      - run: |
          echo "build"
          export GOPATH=$HOME/go
          make vald
          make all
          make vald/sha/update
          make vald/client/node/version/update
          rm -rf vald
      - run: |
          echo "commit and push"
          sha=`make vald/sha/print`
          git config --global user.name 'VDaaS org'
          git config --global user.email 'ci@vdaas.org'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[skip ci] Update [vald sha: ${sha}]"
          git push
      - run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
